# Generated by Django 2.2.1 on 2019-06-20 09:20

from django.db import migrations, models

import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAlipayRealInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alipay_account', models.CharField(max_length=50, unique=True)),
                ('alipay_real_name', models.CharField(max_length=30)),
                ('check_status', models.SmallIntegerField(choices=[(0, '未审核'), (1, '审核通过'), (2, '审核不通过')], default=0)),
                ('check_time', models.BigIntegerField()),
                ('add_time', models.BigIntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='pay_password',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
