# Generated by Django 2.2.1 on 2019-06-20 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pay_password',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
