# Generated by Django 2.2.1 on 2019-06-20 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_url', models.CharField(max_length=120, null=True)),
                ('image_url', models.CharField(max_length=120, null=True)),
                ('shop_market_name', models.CharField(max_length=120)),
                ('shop_floor', models.CharField(max_length=120)),
                ('shop_stalls_no', models.CharField(max_length=120)),
                ('art_no', models.CharField(max_length=20)),
                ('goods_price', models.FloatField()),
                ('goods_color', models.CharField(max_length=10)),
                ('goods_size', models.CharField(default='', max_length=10)),
                ('is_delete', models.BooleanField(default=False)),
                ('add_time', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Logistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logistics_name', models.CharField(max_length=40, unique=True)),
                ('logistics_price', models.FloatField(default=4.0, max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=30, unique=True)),
                ('pay_no', models.CharField(max_length=128, null=True)),
                ('consignee_address', models.CharField(max_length=140)),
                ('consignee_name', models.CharField(max_length=30)),
                ('consignee_phone', models.BigIntegerField()),
                ('sender_address', models.CharField(max_length=140)),
                ('sender_name', models.CharField(max_length=30)),
                ('sender_phone', models.BigIntegerField()),
                ('is_delete', models.BooleanField(default=False)),
                ('logistics_fee', models.FloatField()),
                ('agency_fee', models.FloatField(default=0.0)),
                ('logistics_name', models.CharField(max_length=30, null=True)),
                ('logistics_number', models.CharField(max_length=30, null=True)),
                ('weight', models.FloatField(default='0.0')),
                ('total_price', models.FloatField(default='0.0')),
                ('add_time', models.BigIntegerField()),
                ('order_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
        migrations.CreateModel(
            name='OrderGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_apply_status', models.SmallIntegerField(choices=[(0, '无退款'), (1, '退货退款'), (2, '仅退款'), (3, '换货'), (4, '取消订单')], default=0)),
                ('status', models.IntegerField(choices=[(1, '待付款'), (2, '已付款'), (3, '拿货中'), (4, '已拿货'), (5, '已发货'), (6, '已退款'), (7, '缺货'), (8, '已取消')])),
                ('customer_service_message', models.CharField(max_length=2048, null=True)),
                ('customer_message', models.CharField(max_length=2048, null=True)),
                ('origin_url', models.CharField(max_length=120, null=True)),
                ('shop_market_name', models.CharField(max_length=120)),
                ('shop_floor', models.CharField(max_length=120)),
                ('shop_stalls_no', models.CharField(max_length=120)),
                ('art_no', models.CharField(max_length=20)),
                ('goods_price', models.FloatField()),
                ('goods_color', models.CharField(max_length=30)),
                ('goods_size', models.CharField(max_length=30)),
                ('goods_count', models.IntegerField(default=1)),
                ('add_time', models.BigIntegerField()),
                ('return_logistics_name', models.CharField(max_length=30, null=True)),
                ('return_logistics_number', models.CharField(max_length=40, null=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('goods', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trade.Goods')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderGoods', to='trade.Order')),
            ],
        ),
        migrations.CreateModel(
            name='RefundInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_sn', models.CharField(max_length=128, unique=True)),
                ('refund_money_amount', models.FloatField()),
                ('add_time', models.BigIntegerField()),
                ('order_goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade.OrderGoods')),
            ],
        ),
        migrations.CreateModel(
            name='RefundApply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.BigIntegerField(default=1561022396.6775107)),
                ('refund_apply_type', models.SmallIntegerField(choices=[(0, '无退款'), (1, '退货退款'), (2, '仅退款'), (3, '换货'), (4, '取消订单')])),
                ('apply_message', models.CharField(max_length=256)),
                ('return_logistics_name', models.CharField(max_length=30)),
                ('return_logistics_number', models.CharField(max_length=40)),
                ('orderGoods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_apply', to='trade.OrderGoods')),
            ],
        ),
        migrations.CreateModel(
            name='PlayInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_sn', models.CharField(max_length=128, unique=True)),
                ('pay_no', models.CharField(max_length=128, unique=True)),
                ('money_amount', models.FloatField()),
                ('add_time', models.BigIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade.Order')),
            ],
        ),
    ]
