# Generated by Django 2.2.1 on 2019-06-22 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_auto_20190620_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordergoods',
            name='goods_number',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='ordergoods',
            name='refund_apply_status',
            field=models.SmallIntegerField(choices=[(0, '无售后'), (1, '退货退款'), (2, '仅退款'), (3, '换货'), (4, '取消订单')], default=0),
        ),
        migrations.AlterField(
            model_name='refundapply',
            name='add_time',
            field=models.BigIntegerField(default=1561171338.6431992),
        ),
        migrations.AlterField(
            model_name='refundapply',
            name='refund_apply_type',
            field=models.SmallIntegerField(choices=[(0, '无售后'), (1, '退货退款'), (2, '仅退款'), (3, '换货'), (4, '取消订单')]),
        ),
    ]
