# Generated by Django 2.2.1 on 2019-06-22 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_auto_20190622_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refundapply',
            name='add_time',
            field=models.BigIntegerField(default=1561212055.3240602),
        ),
    ]
