# Generated by Django 2.2.1 on 2019-06-25 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0004_auto_20190622_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refundapply',
            name='add_time',
            field=models.BigIntegerField(default=1561454678.7047038),
        ),
    ]
