# Generated by Django 2.2.1 on 2019-07-06 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_pay_password'),
        ('trade', '0005_auto_20190625_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refundapply',
            name='add_time',
            field=models.BigIntegerField(default=1562408703.8853004),
        ),
        migrations.CreateModel(
            name='TradeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_number', models.CharField(max_length=30, unique=True)),
                ('user_balance', models.FloatField(null=True)),
                ('trade_source', models.SmallIntegerField(choices=[(1, '订单'), (2, '商品'), (3, '充值'), (4, '提现'), (5, '其他费用')])),
                ('message', models.CharField(max_length=256, null=True)),
                ('recharge_number', models.CharField(max_length=64, null=True, unique=True)),
                ('cash_in_out_type', models.SmallIntegerField(choices=[(1, '收入'), (2, '支出')])),
                ('trade_money', models.FloatField()),
                ('is_pass', models.BooleanField(default=False, null=True)),
                ('add_time', models.BigIntegerField()),
                ('is_delete', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.User')),
            ],
        ),
    ]
