# Generated by Django 2.2.1 on 2019-07-07 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0006_auto_20190706_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeinfo',
            name='order_number',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='refundapply',
            name='add_time',
            field=models.BigIntegerField(default=1562470327.8950794),
        ),
    ]
