# Generated by Django 2.2.1 on 2019-07-07 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0007_auto_20190707_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refundapply',
            name='add_time',
            field=models.BigIntegerField(default=1562470433.600125),
        ),
        migrations.AlterField(
            model_name='tradeinfo',
            name='order_number',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='tradeinfo',
            name='recharge_number',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
