# Generated by Django 2.2.1 on 2019-07-21 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0008_auto_20190707_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality_testing_name', models.CharField(max_length=40, unique=True)),
                ('quality_testing_price', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='quality_testing_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='quality_testing_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='refundapply',
            name='add_time',
            field=models.BigIntegerField(default=1563708378.8525305),
        ),
        migrations.AlterField(
            model_name='tradeinfo',
            name='is_pass',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tradeinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
    ]
