# Generated by Django 2.2.1 on 2019-07-23 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0010_auto_20190721_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='refundapply',
            name='goods_counts',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='refundapply',
            name='add_time',
            field=models.BigIntegerField(default=1563892238.2087817),
        ),
        migrations.DeleteModel(
            name='PlayInfo',
        ),
    ]
